// enterprise-app/src/app/home/home.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import {
  IonBadge,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardSubtitle,
  IonCardTitle
} from '@ionic/angular/standalone';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [RouterLink, IonCard, IonCardContent, IonCardHeader, IonCardTitle, IonCardSubtitle, IonBadge],
  template: `
    <div class="page">
      <header class="page-toolbar">
        <span class="page-title">Enterprise Corp</span>
      </header>

      <div class="page-content">

        <!-- Hero banner -->
        <div style="background: linear-gradient(135deg, #1B2A4A 0%, #243860 100%);
                    padding: 36px 28px 32px; color: #fff;">
          <p style="margin: 0 0 6px; font-size: 11px; font-weight: 700; letter-spacing: .12em;
                     text-transform: uppercase; color: #C9921A;">Enterprise Portal</p>
          <h1 style="margin: 0 0 12px; font-size: 30px; font-weight: 700; letter-spacing: -0.5px;">
            Enterprise Corp
          </h1>
          <p style="margin: 0; font-size: 14px; line-height: 1.7; color: #A8BCDA; max-width: 580px;">
            Enterprise host application on <strong style="color:#fff;">Angular 18</strong> consuming the same
            <strong style="color:#fff;">disputes-mfe</strong> (Angular 20) via
            <strong style="color:#fff;">Webpack Module Federation</strong> —
            proving version-agnostic MFE loading.
          </p>
        </div>

        <!-- PoC architecture bar -->
        <div style="background: #0F1E38; padding: 12px 28px; display: flex; align-items: center;
                    gap: 8px; flex-wrap: wrap;">
          <span style="font-size: 11px; font-weight: 700; text-transform: uppercase;
                       letter-spacing: .08em; color: #C9921A;">PoC:</span>
          <span style="font-size: 12px; color: #8A9BC0;">WDP Shell <span style="color:#4A6080;">:4200 (Angular 20)</span></span>
          <span style="color: #4A6080; font-size: 12px;">+</span>
          <span style="font-size: 12px; color: #E8A020; font-weight: 600;">Enterprise Corp <span style="color:#C9921A;">:4202 (Angular 18)</span></span>
          <span style="color: #4A6080; font-size: 12px;">+</span>
          <span style="font-size: 12px; color: #61dafb;">React Enterprise <span style="color:#4A6080;">:4203 (React 18)</span></span>
          <span style="color: #4A6080; font-size: 12px;">→ all consume</span>
          <span style="font-size: 12px; background: rgba(201,146,26,.15); color: #E8A020;
                       padding: 2px 8px; border-radius: 10px; border: 1px solid rgba(201,146,26,.3);">
            disputes-mfe :4201 (Angular 20)
          </span>
        </div>

        <!-- Module cards -->
        <div style="padding: 24px 28px 32px;">
          <p style="margin: 0 0 16px; font-size: 11px; font-weight: 700; text-transform: uppercase;
                     letter-spacing: .1em; color: #7A90B0;">Modules</p>
          <div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(240px,1fr)); gap: 16px;">

            <ion-card button routerLink="/disputes"
                      style="--background: #fff; border-top: 3px solid #C9921A; margin: 0; cursor: pointer;">
              <ion-card-header>
                <div style="font-size: 26px; margin-bottom: 8px;">⚖️</div>
                <ion-card-title style="font-size: 15px; color: #1B2A4A;">Disputes</ion-card-title>
                <ion-card-subtitle style="color: #C9921A; font-size: 11px; font-weight: 700;
                                          text-transform: uppercase; letter-spacing: .06em;">
                  MFE · port 4201
                </ion-card-subtitle>
              </ion-card-header>
              <ion-card-content style="color: #5A7090; font-size: 13px; line-height: 1.5;">
                Live micro-frontend (Angular 20) via Module Federation. Injected with enterprise appContext.
              </ion-card-content>
            </ion-card>

            <ion-card button routerLink="/transactions"
                      style="--background: #fff; border-top: 3px solid #2E6DA4; margin: 0; cursor: pointer;">
              <ion-card-header>
                <div style="font-size: 26px; margin-bottom: 8px;">🔍</div>
                <ion-card-title style="font-size: 15px; color: #1B2A4A;">Transaction Search</ion-card-title>
                <ion-card-subtitle style="color: #2E6DA4; font-size: 11px; font-weight: 700;
                                          text-transform: uppercase; letter-spacing: .06em;">
                  Placeholder
                </ion-card-subtitle>
              </ion-card-header>
              <ion-card-content style="color: #5A7090; font-size: 13px; line-height: 1.5;">
                Search payment history, audit trails, and transaction records across the enterprise.
              </ion-card-content>
            </ion-card>

          </div>
        </div>

      </div>
    </div>
  `
})
export class HomeComponent {}

// enterprise-react-app/src/pages/Home.jsx
import { Link } from 'react-router-dom';

export default function Home() {
  return (
    <div>

      {/* Page header */}
      <div className="page-header">
        <p className="page-header-eyebrow">React Enterprise · Host Application</p>
        <h1 className="page-header-title">React Enterprise App</h1>
        <p className="page-header-desc">
          A <strong style={{ color: '#fff' }}>React 18</strong> host application consuming the
          same <strong style={{ color: '#fff' }}>disputes-mfe</strong> loaded by the Angular hosts —
          via <strong style={{ color: '#fff' }}>Webpack Module Federation</strong>. The MFE is an
          Angular Elements Web Component, completely framework-agnostic. React renders it
          as a native DOM element with its own <code style={{ background: 'rgba(255,255,255,.1)',
          padding: '1px 6px', borderRadius: 3, fontSize: 13 }}>appContext</code>.
        </p>
      </div>

      {/* Info bar */}
      <div className="info-bar">
        <span className="react-badge">⚛ React 18</span>
        <span className="info-bar-sep">·</span>
        <span className="info-bar-item">Webpack 5 Module Federation HOST</span>
        <span className="info-bar-sep">·</span>
        <span style={{ fontSize: 12, color: '#10b981' }}>Port 4203</span>
        <span className="info-bar-sep">·</span>
        <span className="info-bar-item">No Angular, No Ionic</span>
      </div>

      {/* PoC architecture callout */}
      <div style={{ margin: '24px 24px 0', background: '#0d1117', borderRadius: 8,
                    padding: '14px 18px', border: '1px solid #21262d',
                    borderLeft: '4px solid #10b981' }}>
        <p style={{ margin: '0 0 6px', fontSize: 11, fontWeight: 700, textTransform: 'uppercase',
                    letterSpacing: '.08em', color: '#10b981' }}>
          PoC Architecture — Framework Agnostic MFE
        </p>
        <div style={{ display: 'flex', gap: 24, flexWrap: 'wrap' }}>
          {[
            { label: 'WDP Shell',       fw: 'Angular + Ionic', port: '4200', color: '#3880ff' },
            { label: 'Enterprise Corp', fw: 'Angular + Ionic', port: '4202', color: '#C9921A' },
            { label: 'React Enterprise',fw: 'React 18',        port: '4203', color: '#10b981', active: true },
          ].map(h => (
            <div key={h.port} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ width: 8, height: 8, borderRadius: '50%',
                             background: h.active ? '#10b981' : '#21262d',
                             border: `2px solid ${h.color}`, flexShrink: 0 }}></span>
              <span style={{ fontSize: 12, color: h.active ? '#e6edf3' : '#8b949e' }}>
                {h.label}
              </span>
              <span style={{ fontSize: 11, color: h.color }}>:{h.port}</span>
              <span style={{ fontSize: 11, color: '#484f58' }}>({h.fw})</span>
            </div>
          ))}
        </div>
        <p style={{ margin: '10px 0 0', fontSize: 12, color: '#8b949e' }}>
          All three consume <span style={{ color: '#10b981' }}>disputes-mfe :4201</span> —
          same Angular Elements Web Component, different framework hosts, different appContext.
        </p>
      </div>

      {/* Section cards */}
      <p style={{ margin: '24px 24px 12px', fontSize: 11, fontWeight: 700,
                  textTransform: 'uppercase', letterSpacing: '.1em', color: '#94a3b8' }}>
        Modules
      </p>
      <div className="cards-grid" style={{ paddingTop: 0 }}>

        <Link to="/disputes" className="card">
          <div className="card-icon">⚖️</div>
          <p className="card-title">Disputes</p>
          <p className="card-desc">
            Angular Elements Web Component loaded via Module Federation into this React app.
            Proves framework-agnostic MFE consumption.
          </p>
          <span className="card-link">Angular Elements · port 4201 →</span>
        </Link>

        <Link to="/transactions" className="card" style={{ borderTopColor: '#10b981' }}>
          <div className="card-icon">🔍</div>
          <p className="card-title">Transaction Search</p>
          <p className="card-desc">
            Search payment history, audit trails, and transaction records across the enterprise.
          </p>
          <span className="card-link" style={{ color: '#10b981' }}>Placeholder →</span>
        </Link>

      </div>
    </div>
  );
}
