// enterprise-react-app/src/pages/Home.jsx
import { Link } from 'react-router-dom';

export default function Home() {
  return (
    <div>

      {/* Page header */}
      <div className="page-header">
        <p className="page-header-eyebrow">React Enterprise · Host Application</p>
        <h1 className="page-header-title">React Enterprise App</h1>
        <p className="page-header-desc">
          A <strong style={{ color: '#fff' }}>React 18</strong> host application consuming the
          same <strong style={{ color: '#fff' }}>disputes-mfe</strong> loaded by the Angular hosts —
          via <strong style={{ color: '#fff' }}>Webpack Module Federation</strong>. The MFE is an
          Angular Elements Web Component, completely framework-agnostic. React renders it
          as a native DOM element with its own <code style={{ background: 'rgba(255,255,255,.1)',
          padding: '1px 6px', borderRadius: 3, fontSize: 13 }}>appContext</code>.
        </p>
      </div>

      {/* Info bar */}
      <div className="info-bar">
        <span className="react-badge">⚛ React 18</span>
        <span className="info-bar-sep">·</span>
        <span className="info-bar-item">Webpack 5 Module Federation HOST</span>
        <span className="info-bar-sep">·</span>
        <span style={{ fontSize: 12, color: '#10b981' }}>Port 4203</span>
        <span className="info-bar-sep">·</span>
        <span className="info-bar-item">No Angular, No Ionic</span>
      </div>

      {/* PoC architecture callout */}
      <div style={{ margin: '24px 24px 0', background: '#0d1117', borderRadius: 8,
                    padding: '14px 18px', border: '1px solid #21262d',
                    borderLeft: '4px solid #10b981' }}>
        <p style={{ margin: '0 0 6px', fontSize: 11, fontWeight: 700, textTransform: 'uppercase',
                    letterSpacing: '.08em', color: '#10b981' }}>
          PoC Architecture — Framework Agnostic MFE
        </p>
        <div style={{ display: 'flex', gap: 24, flexWrap: 'wrap' }}>
          {[
            { label: 'WDP Shell',       fw: 'Angular + Ionic', port: '4200', color: '#3880ff' },
            { label: 'Enterprise Corp', fw: 'Angular + Ionic', port: '4202', color: '#C9921A' },
            { label: 'React Enterprise',fw: 'React 18',        port: '4203', color: '#10b981', active: true },
          ].map(h => (
            <div key={h.port} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ width: 8, height: 8, borderRadius: '50%',
                             background: h.active ? '#10b981' : '#21262d',
                             border: `2px solid ${h.color}`, flexShrink: 0 }}></span>
              <span style={{ fontSize: 12, color: h.active ? '#e6edf3' : '#8b949e' }}>
                {h.label}
              </span>
              <span style={{ fontSize: 11, color: h.color }}>:{h.port}</span>
              <span style={{ fontSize: 11, color: '#484f58' }}>({h.fw})</span>
            </div>
          ))}
        </div>
        <p style={{ margin: '10px 0 0', fontSize: 12, color: '#8b949e' }}>
          All three consume <span style={{ color: '#10b981' }}>disputes-mfe :4201</span> —
          same Angular Elements Web Component, different framework hosts, different appContext.
        </p>
      </div>

      {/* Section cards */}
      <p style={{ margin: '24px 24px 12px', fontSize: 11, fontWeight: 700,
                  textTransform: 'uppercase', letterSpacing: '.1em', color: '#94a3b8' }}>
        Modules
      </p>
      <div className="cards-grid" style={{ paddingTop: 0 }}>

        <Link to="/disputes" className="card">
          <div className="card-icon">⚖️</div>
          <p className="card-title">Disputes</p>
          <p className="card-desc">
            Angular Elements Web Component loaded via Module Federation into this React app.
            Proves framework-agnostic MFE consumption.
          </p>
          <span className="card-link">Angular Elements · port 4201 →</span>
        </Link>

        <Link to="/transactions" className="card" style={{ borderTopColor: '#10b981' }}>
          <div className="card-icon">🔍</div>
          <p className="card-title">Transaction Search</p>
          <p className="card-desc">
            Search payment history, audit trails, and transaction records across the enterprise.
          </p>
          <span className="card-link" style={{ color: '#10b981' }}>Placeholder →</span>
        </Link>

      </div>
    </div>
  );
}

// wdp-app/wdp-shell/src/app/home/home.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import {
  IonContent,
  IonHeader,
  IonMenuButton,
  IonTitle,
  IonToolbar
} from '@ionic/angular/standalone';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [IonContent, IonHeader, IonMenuButton, IonTitle, IonToolbar, RouterLink],
  template: `
    <div class="ion-page">
      <ion-header>
        <ion-toolbar color="primary">
          <ion-menu-button slot="start"></ion-menu-button>
          <ion-title>WDP Shell</ion-title>
        </ion-toolbar>
      </ion-header>

      <ion-content>
        <div style="padding: 24px 20px; max-width: 860px; margin: 0 auto;">

          <!-- Hero -->
          <div style="margin-bottom: 32px;">
            <h1 style="margin: 0 0 6px; font-size: 28px; font-weight: 700; color: #1a1a1a;">
              WDP Shell
            </h1>
            <p style="margin: 0 0 4px; font-size: 13px; font-weight: 600; text-transform: uppercase;
                       letter-spacing: .06em; color: #3880ff;">
              WDP Team — Host Application
            </p>
            <p style="margin: 12px 0 0; font-size: 15px; line-height: 1.7; color: #444;">
              The WDP team's primary host application. It owns the page shell, routing, and Ionic
              UI chrome. Micro-frontends are loaded at runtime via
              <strong>Webpack Module Federation</strong> — each MFE runs as an independent Angular
              Elements Web Component served from its own origin.
            </p>
          </div>

          <!-- Architecture note -->
          <div style="background: #f0f4ff; border-left: 4px solid #3880ff; border-radius: 6px;
                      padding: 14px 16px; margin-bottom: 32px;">
            <p style="margin: 0 0 6px; font-weight: 700; font-size: 13px; color: #3880ff;">
              PoC Architecture
            </p>
            <p style="margin: 0; font-size: 13px; line-height: 1.6; color: #333;">
              Two independent host applications — <strong>WDP Shell</strong> (port 4200) and
              <strong>Enterprise Corp</strong> (port 4202) — both consume the same
              <code style="background:#dde8ff; padding: 1px 5px; border-radius: 3px;">disputes-mfe</code>
              remote (port 4201), each injecting its own
              <code style="background:#dde8ff; padding: 1px 5px; border-radius: 3px;">appContext</code>.
              This proves the MFE is host-agnostic.
            </p>
          </div>

          <!-- Section cards -->
          <h2 style="margin: 0 0 14px; font-size: 14px; font-weight: 700; text-transform: uppercase;
                     letter-spacing: .06em; color: #666;">
            Sections
          </h2>
          <div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 14px;">

            <a routerLink="/disputes" style="text-decoration: none;">
              <div style="border: 1px solid #dde8ff; border-radius: 10px; padding: 20px;
                          background: #fff; cursor: pointer; transition: box-shadow .15s;"
                   onmouseover="this.style.boxShadow='0 4px 14px rgba(56,128,255,.15)'"
                   onmouseout="this.style.boxShadow='none'">
                <div style="font-size: 28px; margin-bottom: 10px;">⚖️</div>
                <p style="margin: 0 0 6px; font-weight: 700; font-size: 15px; color: #1a1a1a;">
                  Disputes
                </p>
                <p style="margin: 0; font-size: 13px; color: #666; line-height: 1.5;">
                  Micro-frontend loaded via Module Federation. Displays live dispute records
                  from the mock-api and exposes the injected appContext.
                </p>
                <span style="display: inline-block; margin-top: 10px; font-size: 12px; font-weight: 600;
                             color: #3880ff;">
                  Angular Elements · port 4201 →
                </span>
              </div>
            </a>

            <a routerLink="/users" style="text-decoration: none;">
              <div style="border: 1px solid #e8f5e9; border-radius: 10px; padding: 20px;
                          background: #fff; cursor: pointer; transition: box-shadow .15s;"
                   onmouseover="this.style.boxShadow='0 4px 14px rgba(46,125,50,.12)'"
                   onmouseout="this.style.boxShadow='none'">
                <div style="font-size: 28px; margin-bottom: 10px;">👥</div>
                <p style="margin: 0 0 6px; font-weight: 700; font-size: 15px; color: #1a1a1a;">
                  User Management
                </p>
                <p style="margin: 0; font-size: 13px; color: #666; line-height: 1.5;">
                  Manage users, roles, and permissions within the WDP platform.
                </p>
                <span style="display: inline-block; margin-top: 10px; font-size: 12px; font-weight: 600;
                             color: #2e7d32;">
                  Placeholder →
                </span>
              </div>
            </a>

            <a routerLink="/org" style="text-decoration: none;">
              <div style="border: 1px solid #fff3e0; border-radius: 10px; padding: 20px;
                          background: #fff; cursor: pointer; transition: box-shadow .15s;"
                   onmouseover="this.style.boxShadow='0 4px 14px rgba(230,81,0,.1)'"
                   onmouseout="this.style.boxShadow='none'">
                <div style="font-size: 28px; margin-bottom: 10px;">🏢</div>
                <p style="margin: 0 0 6px; font-weight: 700; font-size: 15px; color: #1a1a1a;">
                  Org Management
                </p>
                <p style="margin: 0; font-size: 13px; color: #666; line-height: 1.5;">
                  Configure organisation settings, tenants, and hierarchy within WDP.
                </p>
                <span style="display: inline-block; margin-top: 10px; font-size: 12px; font-weight: 600;
                             color: #e65100;">
                  Placeholder →
                </span>
              </div>
            </a>

          </div>
        </div>
      </ion-content>
    </div>
  `
})
export class HomeComponent {}
